### PR TITLE
Add Ruby 2.7+ support

### PR DESCRIPTION
**Pull request by Volosh1n**
Probably it should be 3+ support, but let's start from simplier changes

- changed .ruby-version to 2.7.0
- added splat where it's needed after bumpt to 2.7
- renamed directory for CircleCI (in honor of gem's name)
- fixed typo in changelog's filename
- removed Gemfile.lock
- bumped of rubocop version, since previous one does not support Ruby 2.7+

Hope it fits well

### CODE REVIEW

**Comment by differencialx** [comment]
Hi @Volosh1n, thanks a lot for this PR
Could you also please change circleCI config file to process builds against 2.6 and 2.7 versions in order to be sure that this changes is compatible with both versions.
I wanted to do it by myself, but I don't have an access to your branch.
I found such [solution](https://gist.github.com/MothOnMars/1c4ef90e33d5b23691874f4c0fdd72fe), hope it will help you.

**Comment by Volosh1n** [comment]
@differencialx yep. Thank you. Will fix that soon.

**Comment by Volosh1n** [comment]
I applied some changes and added summary to description of this PR, but I'm not sure about CircleCI config since tests don't automatically starts now in open-source projects on GIthub. Only maintainers are able to run it.

**Comment by Volosh1n** [comment]
Also added step with running rubocop to CI

**Review by differencialx — APPROVED** [review]

**Pull request merged**
